version: "2"
services:
  openresty_openssl10:
    build:
      context: .
      args:
        RESTY_VERSION: "1.13.6.2rc1"
        RESTY_OPENSSL_VERSION: "1.0.2o"
    volumes:
      - .:/app
  openresty_openssl11:
    build:
      context: .
      args:
        RESTY_VERSION: "1.13.6.2rc1"
        RESTY_OPENSSL_VERSION: "1.1.0h"
    volumes:
      - .:/app
  openresty_package:
    build:
      context: .
      dockerfile: Dockerfile-package
    volumes:
      - .:/app
  luajit_openssl10:
    build:
      context: .
      dockerfile: Dockerfile-luajit
      args:
        OPENSSL_PACKAGE: "libssl1.0-dev"
    volumes:
      - .:/app
  luajit_openssl11:
    build:
      context: .
      dockerfile: Dockerfile-luajit
      args:
        OPENSSL_PACKAGE: "libssl-dev"
    volumes:
      - .:/app
